exp_name: 'bp4d_disfa'
# source domain
source_domain: 'bp4d'
source_data_root: '/workspace/dataset'
source_train_list: './data/bp4d/total.csv'
# target domain
target_domain: 'disfa'
target_data_root: '/workspace/dataset/DISFA/Images_left'
fold: 1
target_train_list: './data/disfa/train_1f.csv'
target_test_list: './data/disfa/test_1f.csv'

input_shape: [3, 224, 224]
au_list: [1, 2, 4, 6, 12]
class_num: 5
batch_size: 128
number_works: 8
seed: 2025
epochs: 20
lr_init: 0.0008