# Experiment Setup
exp_name: 'disfa2bp4d'
seed: 2025
stage: 'one'
train_or_test: 'train'
checkpoint_path: ''

# Dataset Configuration
## Source Domain
source_domain: 'disfa'
source_data_root: '/mnt/sda/yiren/data/DISFA/Images_left'
source_train_list: './data/disfa/total.csv'
source_val_list: './data/disfa/total_val.csv'
## Target Domain
fold: 1
target_domain: 'bp4d'
target_data_root: '/mnt/sda/yiren/data'
target_train_list: './data/bp4d/train_1f.csv'
target_test_list: './data/bp4d/test_1f.csv'
## General Data Parameters
img_size: 256
input_shape: [3, 224, 224]
au_list: [1, 2, 4, 6, 12]
class_num: 5

# Training Parameters
batch_size: 256
number_works: 8
epochs: 10
optimizer: 'adamw'
lr_init: 0.0001
momentum: 0.9
weight_decay: 0.0005
source_cl_loss_weight: 0.1

# Model Parameters
backbone: 'RN50' # RN50, ViT-B/16
drop_rate: 0.3
neighbor_num: 4

# CoOp
n_ctx: 16
ctx_init: ''
csc: False # class-specific context (False or True)
ctp: 'end' # class token position (end or middle)
