# experiment name
exp_name: 'gft2bp4d'
stage: 'one'
train_or_test: 'train'
checkpoint_path: '/workspace/projects/uda/Unsupervised-Domain-Adaptation/results/bp4d_gft/train_cross_fold_1_seed_2019_date_2025-04-11_10_14-31_AM/best_model_fold1.pth'
# source domain
source_domain: 'gft'
source_data_root: '/workspace/dataset'
source_train_list: './data/gft/total.csv'
# target domain
target_domain: 'bp4d'
target_data_root: '/workspace/dataset'
fold: 2
target_train_list: './data/bp4d/train_2f.csv'
target_test_list: './data/bp4d/test_2f.csv'

input_shape: [3, 224, 224]
au_list: [1, 2, 4, 6, 10, 12, 14, 15, 23, 24]
class_num: 10
batch_size: 128
number_works: 8
seed: 2019
epochs: 15
lr_init: 0.0001
optimizer: 'adamw'
weight_decay: 0.0005
backbone: 'RN50' # RN50, ViT-B/16
source_cl_loss_weight: 0.1
